name: Sync to Public Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3

      - name: Remove PHP files
        run: |
          find . -name "*.php" -type f -delete

      - name: Remove YAML files
        run: |
          find . -name "*.yml" -type f -delete
          find . -name "*.yaml" -type f -delete

      - name: Ensure folder exists in public repo
        run: |
          mkdir -p 10Store

      - name: Copy files to public repo
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.WRITE_TOKEN }}
        with:
          source_file: "./"
          destination_repo: "draydenthemiiyt-maker/draymusic.github.io"
          destination_folder: "10Store"
          user_email: "draydenthemiiyt@gmail.com"
          user_name: "draydenthemiiyt-maker"
